main_app/urls.py
from django.urls import path, include
from . import views




	
urlpatterns = [
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),
	path('properties/', views.properties_index, name='index'),
    path('properties/<int:property_id>/', views.properties_detail, name='detail'),
    path('properties/add/', views.PropertyAdd.as_view(), name='properties_add'),
    path('properties/<int:pk>/update/', views.PropertyUpdate.as_view(), name='properties_update'),
    path('properties/<int:pk>/delete/', views.PropertyDelete.as_view(), name='properties_delete'),
    path('properties/<int:property_id>/add_renting/', views.add_renting, name='add_renting'),
    
    path('cats/<int:property_id>/add_photo/', views.add_photo, name='add_photo'),
    
    path('properties/<int:property_id>/assoc_amenity/<int:amenity_id>/', views.assoc_amenity, name='assoc_amenity'),
    path('properties/<int:property_id>/unassoc_amenity/<int:amenity_id>/', views.unassoc_amenity, name='unassoc_amenity'),
    path('amenities/', views.AmenityList.as_view(), name='amenities_index'),
    path('amenities/<int:pk>/', views.AmenityDetail.as_view(), name='amenities_detail'),
    path('amenities/create/', views.AmenityCreate.as_view(), name='amenities_create'),
    path('amenities/<int:pk>/update/', views.AmenityUpdate.as_view(), name='amenities_update'),
    path('amenities/<int:pk>/delete/', views.AmenityDelete.as_view(), name='amenities_delete'),
    path('accounts/signup/', views.signup, name='signup'),
     
    
]

realstate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

PURPOSES = (
  ('H', 'House Sharing'),
  ('R', 'Room Sharing'),
  ('E', 'Entire property'),
)

# Create your models here.
class Amenity(models.Model):
  name = models.CharField(max_length=100)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('amenities_detail', kwargs={'pk': self.id})



class Property(models.Model):
  title = models.CharField(max_length=50)
  address = models.TextField(max_length=200)
  suburb = models.CharField(max_length=50)
  state = models.CharField(max_length=3)
  postcode = models.IntegerField()
  details = models.TextField(max_length=200)
  price = models.IntegerField()
  amenities = models.ManyToManyField(Amenity)
  user = models.ForeignKey(User, on_delete=models.CASCADE)


  def __str__(self):
    return f'{self.title} ({self.id})'
  
  def get_absolute_url(self):
    return reverse('detail', kwargs={'property_id': self.id})
  
class Renting(models.Model):
    available_date = models.DateField('availability Date')
    purpose = models.CharField(
      max_length=1,
      choices=PURPOSES,
      default=PURPOSES[0][0]
      )
    
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.get_purpose_display()} on {self.available_date}"
    
    
    class Meta:
     ordering = ['-available_date']
     
     
     
class Photo(models.Model):
  url = models.CharField(max_length=200)
  property = models.ForeignKey(Property, on_delete=models.CASCADE)

  def __str__(self):
        return f"Photo for property_id: {self.property_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Renting

class RentingForm(ModelForm):
  class Meta:
    model = Renting
    fields = ['available_date', 'purpose']

main_app/views.py
import os
import uuid
import boto3
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .models import Property, Amenity, Photo
from .forms import RentingForm

import json
from django.conf import settings



# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')
  
@login_required
def properties_index(request):
    properties = Property.objects.filter(user=request.user)
    return render(request, 'properties/index.html', {
        'properties': properties
    })
    
@login_required
def properties_detail(request, property_id):
    property = Property.objects.get(id=property_id)
    id_list = property.amenities.all().values_list('id')
    amenities_property_doesnt_have = Amenity.objects.exclude(id__in=id_list)
    renting_form = RentingForm()
    return render(request, 'properties/detail.html', {
        'property':property,
        'renting_form': renting_form,
        'amenities': amenities_property_doesnt_have

    })

class PropertyAdd(CreateView):
    model = Property
    fields = ['title', 'address', 'suburb', 'state', 'postcode', 'details', 'price']
    def form_valid(self, form):
      form.instance.user = self.request.user 
      return super().form_valid(form)
    
class PropertyUpdate(UpdateView):
  model = Property
  fields = ['title', 'address', 'suburb', 'state', 'postcode', 'details', 'price']

class PropertyDelete(DeleteView):
  model = Property
  success_url = '/properties'
    

def add_renting(request, property_id):
    form = RentingForm(request.POST)
  # validate the form
    if form.is_valid():
        new_renting = form.save(commit=False)
        new_renting.property_id = property_id
        new_renting.save()
    return redirect('detail', property_id=property_id)

class AmenityList(ListView):
  model = Amenity

class AmenityDetail(DetailView):
  model = Amenity

class AmenityCreate(CreateView):
  model = Amenity
  fields = '__all__'

class AmenityUpdate(UpdateView):
  model = Amenity
  fields = ['name']

class AmenityDelete(DeleteView):
  model = Amenity
  success_url = '/amenities'     

@login_required
def assoc_amenity(request, property_id, amenity_id):
    Property.objects.get(id=property_id).amenities.add(amenity_id)
    return redirect('detail', property_id=property_id)
  
@login_required
def unassoc_amenity(request, property_id, amenity_id):
    Property.objects.get(id=property_id).amenities.remove(amenity_id)
    return redirect('detail', property_id=property_id)
  
@login_required 
def add_photo(request, property_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, property_id=property_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('detail', property_id=property_id)
  

def signup(request):
  error_message = ''
  form = UserCreationForm(request.POST)
  if request.method == 'POST':
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div class="container-about'">

    <h1 class="about-test">About the UniMate</h1>
    <div class="about-img">
        <img src="{% static 'images/illustration-about.png' %}" alt="">
    </div>
    <div class="about-text">
    <hr>
    <h3>How Could We help you?</h3>
    <p>
        Find Your Ideal Room:Tired of spending countless hours searching for suitable student housing options? With CalUnimate, you can effortlessly browse through a curated list of available shared rooms and apartments near your university.
    </p>
    <p>
        Connect with Potential Housemates: Finding the right housemate can make all the difference in creating a comfortable and enjoyable living environment. 

    </p>
    <p>
        List Your Room for Rent: Have a spare room to offer? As a user, you have the option to list your available room for rent on CalUnimate.Including rent amount, amenities, and any specific requirements you might have for potential tenants.
    </p>
    <p>
        Share Amenities and Property Features: CalUnimate understands that student living is about more than just a room; it's about the entire experience. With our platform, you can showcase the amenities your property provides, whether it's high-speed internet, laundry facilities, a gym, or a cozy communal lounge. Highlighting these features helps potential tenants make informed decisions about their future home.

    </p>
    <p>
        Explore Rental History: As a user, you can access the rental history of a property, giving you insight into its past occupants and their experiences.

    </p>
</div>

 </div>

    <!-- <footer>All Rights Reserved, &copy; 2023 UniMate</footer> -->
 {% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>UniMate</title>
   <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    /> 
    <link rel="stylesheet" type="text/css"href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" type="text/css"href="{% static 'css/about.css' %}"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <div class="logo-container">
            <a href="{% url 'home' %}"
              ><img
                class="logo"
                src="{% static 'images/logo-unimate.png' %}"
                alt="Logo"
            /></a>
          </div>
          <input id="menu-toggle" type="checkbox" />
          <label class='menu-button-container' for="menu-toggle">
          <div class='menu-button'></div>
          </label>
          <ul class="menu">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'amenities_create' %}">Add an Amenity</a></li>
            <li><a href="{% url 'amenities_index' %}">View All Amenities</a></li>
            <li><a href="{% url 'properties_add' %}">Add a new Property</a></li>
            <li><a href="{% url 'index' %}">View All Properties</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
          
            <li ><a href="{% url 'login' %}">Log In</a></li>
            <li ><a href="{% url 'signup' %}">Sign Up</a></li>
            
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="page-footer-container">
        <div class="footer-logo">
          <div>
            <img src="{% static 'images/logo-unimate-blue.png' %}" alt="" />
          </div>
          <hr />
        </div>
        <div class="Footer-socialMedias">
          <img
            src="{% static 'images/icons-social-media/facebook.png' %}"
            alt=""
          />
          <img
            src="{% static 'images/icons-social-media/instagram.png' %}"
            alt=""
          />
          <img
            src="{% static 'images/icons-social-media/twitter.png' %}"
            alt=""
          />
          <img
            src="{% static 'images/icons-social-media/youtube.png' %}"
            alt=""
          />
        </div>
        <div class="footer-text">
          <p>All Rights Reserved, &copy; 2023 UniMate</p>
        </div>
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div>
<section id="section1" data-nav="Section 1" class="your-active-class">
     
    <div class="section1-left-col">
        <div class="section1-text">
            <h2>
                Welcome to Your Ideal Uni life
               </h2>
             <p>
                Are you ready to embark on an unforgettable journey through your college years? At UniMate, we're here to make sure your student experience is nothing short of amazing.
             </p>
             
              <a href="{% url 'about'%}">
                <button class="common-btn" id="">
                  Find Out More 
                </button> 
              </a>
           </div>
     
    </div>
      <div class="section1-right-col">
        <img class="" src="{% static 'images/section1-illustration.png' %}" alt="Logo">
        
      </div>
    
  </section>

  <section id="section2" data-nav="Section 2">
    <h2 id="section2-h2">What We Offer in UniMate?</h2>
      <div class="section2-container">
      
        <div class="section2-col">
            <div class="circle">
          <img src="{% static 'images/fi-br-world.png' %}" alt="">
            </div>
            <h4>
                Exploration
            </h4>
            <p>
                College is a time for growth, learning, and exploring. We're here to support your journey every step of the way.
            </p>
        </div>
        <div class="section2-col">
            <div class="circle">
            <img src="{% static 'images/fi-br-map-marker-plus.png' %}" alt="">
            </div>  
            <h4>
                Community
            </h4>
              <p>
                College life is not just about hitting the books; it's about forming unforgettable memories
              </p>
        </div>
        <div class="section2-col">
            <div class="circle">
            <img src="{% static 'images/fi-br-bookmark.png' %}" alt="">
            </div>
            <h4>
                Affordability
            </h4>
            <p>
                We understand the financial challenges of student life. That's why we offer different range for the options
            </p>
        </div>
          
      </div>
  </section>
  <section id="section3" data-nav="Section 3">
        <div class="section3-text">
          <h1 id="section3-title"> WHAT OUR USERS ARE SAYING</h1>
    
            <h2>
              "I love how Unimate caters to student needs. It's more than just a housing search platform; it's a community. I connected with fellow students and even found a roommate who shares my passion for art. Unimate is a game-changer!"

            </h2>
            <h3 id="section3-name">
              Isabella S. (5/5 stars)
            </h3>
        </div>
    
   
  </section>
</div>
 
   
 {% endblock %}

main_app/templates/main_app/amenity_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Amenity</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'amenities_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/amenity_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Amenity Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ amenity.name }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'amenities_update' amenity.id %}">Edit</a>
        <a href="{% url 'amenities_delete' amenity.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/amenity_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Amenity</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/amenity_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Amenity List</h1>

{% for amenity in amenity_list %}
  <a href="{% url 'amenities_detail' amenity.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ amenity.name }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/property_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Remove Property</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.title }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="">
    <a href="{% url 'detail' property.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/property_form.html
{% extends 'base.html' %}

{% block content %}


{% if object %}
    <h1>Edit <span class="teal-text">{{object.title}}</span></h1>
{% else %}
    <h1>Add a Property</h1>
{% endif %}

  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Done" class="btn">
  </form>
{% endblock %}

main_app/templates/properties/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Property Features</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ property.title }}</span>
                <p>Address: {{ property.address|linebreaks }}</p>
                <p>Suburb: {{ property.suburb }}</p>
                <p>State: {{ property.state }}</p>
                <p>Postcode: {{ property.postcode }}</p>
                <p>Property Details: {{ property.details|linebreaks }}</p>
                {% if property.price > 0 %}
                <p>Weekly rent: ${{ property.price }}</p>
                {% else %}
                <p>Try a higher price!</p>
                {% endif %}
            </div>
           
            <div class="card-action">
                <a href="{% url 'properties_update' property.id %}">Amend Details</a>
                <a href="{% url 'properties_delete' property.id %}">Remove Property</a>
            </div>
        </div>
        <div class="google-map">
            <iframe src="https://maps.google.com/maps?output=embed&amp;q={{ property.address}} {{ property.suburb }} {{ property.state }} {{ property.postcode }} " width="500"
                height="400">
            </iframe>
        </div> 
        {% for photo in property.photo_set.all %}
        <img class="responsive-img card-panel" src="{{photo.url}}">
        {% empty %}
        <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        {% endfor %}
        <form action="{% url 'add_photo' property.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
            {% csrf_token %}
            <input type="file" name="photo-file">
            <br><br>
            <button type="submit" class="btn">Upload Photo</button>
        </form>
    </div>

    <div class="col s6">
        <form action="{% url 'add_renting' property.id %}" method="POST">
            {% csrf_token %}
            {{ renting_form.as_p }}
            <input type="submit" class="btn" value="Add Availibility">
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Availability Date</th>
                    <th>Purpose</th>
                </tr>
            </thead>
            <tbody>
                {% for renting in property.renting_set.all %}
                <tr>
                    <td>{{renting.available_date}}</td>
                    <td>{{renting.get_purpose_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
    <div class="col s6">
        <h3>{{ property.title }}'s Amenities</h3>
        {% if property.amenities.count %}
        {% for amenity in property.amenities.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    {{ amenity.name }}
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'unassoc_amenity' property.id amenity.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn">Remove</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>Unfortunately, this property does not have any of the listed amenities.</h5>
        {% endif %}
    </div>
    <div class="col s6">
        <h3>Available Amenities</h3>
        {% if amenities.count %}
        {% for amenity in amenities.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    {{ amenity.name }}
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'assoc_amenity' property.id amenity.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn">Add</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>{{property.title}} Already Has All Amenities Available</h5>
        {% endif %}
    </div>
</div>

<script>
    const dateEl = document.getElementById('id_available_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    const selectEl = document.getElementById('id_purpose');
    M.FormSelect.init(selectEl);

</script>
{% endblock %}

main_app/templates/properties/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Properties List</h1>

{% for property in properties %}
<div class="card">
    <a href="{% url 'detail' property.id %}">
        <div class="card-content">
            <span class="card-title">{{ property.title }}</span>
            <p>Address: {{ property.address|linebreaks }}</p>
            <p>Suburb: {{ property.suburb }}</p>
            <p>State: {{ property.state }}</p>
            <p>Postcode: {{ property.postcode }}</p>
            <p>Property Details: {{ property.details|linebreaks }}</p>
            {% if property.price > 0 %}
            <p>Weekly rent: ${{ property.price }}</p>
            {% else %}
            <p>Try a higher price!</p>
            {% endif %}
        </div>
    </a>
</div>
{% endfor %}

{% endblock %}